name: Deploy production

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ap-northeast-1
  ECS_CLUSTER: test_ecs_batch
  ENVIRONMENT: prod

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/test_ecs_batch_github_actions_role
          aws-region: ${{ env.AWS_REGION }}

      - uses: kayac/ecspresso@v2
        with:
          version: v2.2.4
      - name: task update
        run: |
          ecspresso register --config ecspresso/ecspresso.jsonnet
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
      
      - uses: Songmu/ecschedule@main
      - run: |
          ecschedule -conf ecschedule/ecschedule.jsonnet apply -all -prune
        env: 
          SUBNET_IDS: ${{ vars.SUBNET_IDS }}
          SECURITY_GROUP_IDS: ${{ vars.SECURITY_GROUP_IDS }}

